-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module ChatAPI.Mutation exposing (..)

import ChatAPI.InputObject
import ChatAPI.Interface
import ChatAPI.Object
import ChatAPI.Scalar
import ChatAPI.ScalarCodecs
import ChatAPI.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode exposing (Decoder)


type alias SendMessageRequiredArguments =
    { content : String
    , author : String
    }


sendMessage :
    SendMessageRequiredArguments
    -> SelectionSet decodesTo ChatAPI.Object.Message
    -> SelectionSet decodesTo RootMutation
sendMessage requiredArgs object_ =
    Object.selectionForCompositeField "sendMessage" [ Argument.required "content" requiredArgs.content Encode.string, Argument.required "author" requiredArgs.author Encode.string ] object_ identity
