-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module ChatAPI.ScalarCodecs exposing (..)

import ChatAPI.Scalar exposing (defaultCodecs)
import Json.Decode as Decode exposing (Decoder)


type alias Id =
    ChatAPI.Scalar.Id


codecs : ChatAPI.Scalar.Codecs Id
codecs =
    ChatAPI.Scalar.defineCodecs
        { codecId = defaultCodecs.codecId
        }
