version: 2
jobs:
  build:
    docker:
      - image: fpco/stack-build
    working_directory: ~/app
    steps:
      - checkout

      - restore_cache:
          keys:
            - stack-work-cache-{{ arch }}-{{ checksum "server/stack.yaml" }}-{{ checksum "server/package.yaml" }}
            - stack-cache-{{ arch }}-{{ checksum "server/stack.yaml" }}-{{ checksum "server/package.yaml" }}

      - run:
          name: Workaround for GCC bug affecting static compilation
          command: |
            # More info about this workaround:
            # - https://www.fpcomplete.com/blog/2016/10/static-compilation-with-stack
            # - https://bugs.launchpad.net/ubuntu/+source/gcc-4.4/+bug/640734
            cp /usr/lib/gcc/x86_64-linux-gnu/7/crtbeginT.o /usr/lib/gcc/x86_64-linux-gnu/7/crtbeginT.o.orig
            cp /usr/lib/gcc/x86_64-linux-gnu/7/crtbeginS.o /usr/lib/gcc/x86_64-linux-gnu/7/crtbeginT.o

      - run:
          name: Configure Stack
          command: |
            cd server
            stack config set system-ghc --global true

      - run:
          name: Statically compile Yesod app
          command: |
            cd server
            stack --local-bin-path ~/app/server/dist install --ghc-options '-optl-static -fPIC'

      - run:
          name: Run tests
          command: |
            cd server
            stack test

      - save_cache:
          key: stack-work-cache-{{ arch }}
          paths:
            - ~/app/server/.stack-work/-{{ checksum "server/stack.yaml" }}-{{ checksum "server/package.yaml" }}
      - save_cache:
          key: stack-cache-{{ arch }}-{{ checksum "server/stack.yaml" }}-{{ checksum "server/package.yaml" }}
          paths:
            - ~/.stack/

      - store_artifacts:
          path: ~/app/server/dist

      - run:
          name: Setup Heroku
          command: bash .circleci/setup-heroku.sh

      - add_ssh_keys:
          fingerprints:
            - "34:e6:c0:32:7f:74:bf:19:0a:3a:09:52:e6:6e:12:52"

      - deploy:
          name: Deploy Master to Heroku
          command: |
            if [ "${CIRCLE_BRANCH}" == "main" ]; then
              git config --global user.email "hvivianshaw@gmail.com"
              git config --global user.name "vivshaw (CI)"
              git checkout -b deploy
              git add -f ~/app/server/dist/herc-server
              git status
              git commit -m "Deployment: Add herc-server executable"
              git push -f heroku deploy:master
            fi
