type Message {
  content: String!
  author: String!
  authorUuid: String!
}

type Query {
  messages(): [Message!]!
}

type Mutation {
  sendMessage(content: String!, author: String!, authorUuid: String!): Message!
}

type Subscription {
  messageSent: Message!
}
