-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module ChatAPI.Object.Message exposing (..)

import ChatAPI.InputObject
import ChatAPI.Interface
import ChatAPI.Object
import ChatAPI.Scalar
import ChatAPI.ScalarCodecs
import ChatAPI.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


content : SelectionSet String ChatAPI.Object.Message
content =
    Object.selectionForField "String" "content" [] Decode.string


author : SelectionSet String ChatAPI.Object.Message
author =
    Object.selectionForField "String" "author" [] Decode.string
